## Gathering OTLY Twitter Mention Data
In this section we will be using SNScrape to gather twitter data surrounding OTLY's IPO date.

In [1]:
# Import libraries.
import os
import pandas as pd
import matplotlib

In [2]:
# Setting variables to be used in format string command below
tweet_count = 100000
text_query = "OTLY"
since_date = "2021-05-20"
until_date = "2021-08-20"

# Using OS library to call CLI commands in Python
os.system('snscrape --jsonl --max-results {} --since {} twitter-search "{} until:{}"> text-query-tweets.json'.format(tweet_count, since_date, text_query, until_date))

0

In [3]:
# Reads the json generated from the CLI command above and creates a pandas dataframe
otly_tweets_df = pd.read_json('text-query-tweets.json', lines=True)

# Displays first 5 entries from dataframe
display(otly_tweets_df.describe())
otly_tweets_df.head()

,id,replyCount,retweetCount,likeCount,quoteCount,conversationId,retweetedTweet,inReplyToTweetId
count,5.376000e+03,5376.000000,5376.000000,5376.000000,5376.000000,5.376000e+03,0.0,1.315000e+03
mean,1.408912e+18,0.744234,0.394531,5.151786,0.106585,1.408725e+18,NaN,1.408324e+18
std,1.066755e+16,3.035521,2.711430,22.105347,0.633327,1.093777e+16,NaN,9.871203e+15
min,1.395167e+18,0.000000,0.000000,0.000000,0.000000,1.321816e+18,NaN,1.358102e+18
25%,1.399439e+18,0.000000,0.000000,0.000000,0.000000,1.399024e+18,NaN,1.400790e+18
50%,1.406260e+18,0.000000,0.000000,1.000000,0.000000,1.406011e+18,NaN,1.405944e+18
75%,1.416831e+18,1.000000,0.000000,3.000000,0.000000,1.416511e+18,NaN,1.415444e+18
max,1.428504e+18,128.000000,119.000000,927.000000,25.000000,1.428504e+18,NaN,1.428453e+18

,_type,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,snscrape.modules.twitter.Tweet,https://twitter.com/aboutheoptions/status/1428...,2021-08-19 23:46:17+00:00,$OTLY Oatly Group AB (OTLY) upgraded to Outper...,$OTLY Oatly Group AB (OTLY) upgraded to Outper...,1428503617905074182,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,3,...,None,NaN,None,NaN,None,None,None,None,None,[OTLY]
1,snscrape.modules.twitter.Tweet,https://twitter.com/Capybara_Stock/status/1428...,2021-08-19 23:36:07+00:00,WL上昇率TOP10\n$AEYE アクセシビリティSaaS9.53%\n$SNPS EDA...,WL上昇率TOP10\n$AEYE アクセシビリティSaaS9.53%\n$SNPS EDA...,1428501059673083907,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,13,...,None,NaN,None,NaN,None,None,None,None,None,"[AEYE, SNPS, WIX, NFE, NFLX, INMD, NVDA, YQ, O..."
2,snscrape.modules.twitter.Tweet,https://twitter.com/PlantFinance/status/142846...,2021-08-19 20:59:53+00:00,Plant Based Companies and Public Markets Today...,Plant Based Companies and Public Markets Today...,1428461741952831493,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,9,...,None,NaN,None,NaN,None,None,None,None,None,"[PLNT, ELMT, ODD, OTLY, RSF, FEEL, NEXE]"
3,snscrape.modules.twitter.Tweet,https://twitter.com/haitoukanri/status/1428457...,2021-08-19 20:42:13+00:00,Android版配当管理アプリをアップデートしました✨\n\nアップデート情報\n\n【バー...,Android版配当管理アプリをアップデートしました✨\n\nアップデート情報\n\n【バー...,1428457295113973763,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,3,30,...,"[{'_type': 'snscrape.modules.twitter.Photo', '...",NaN,None,NaN,None,None,None,None,None,None
4,snscrape.modules.twitter.Tweet,https://twitter.com/jiggycapital/status/142845...,2021-08-19 20:26:17+00:00,8/19 Hi/Lo/Interesting\n\n$wix 211% (+6%)\n$ap...,8/19 Hi/Lo/Interesting\n\n$wix 211% (+6%)\n$ap...,1428453288249372678,"{'_type': 'snscrape.modules.twitter.User', 'us...",0,0,1,...,None,NaN,None,1.428453e+18,"{'_type': 'snscrape.modules.twitter.User', 'us...",None,None,None,None,"[wix, app, nflx, nvda, otly, tigr, rmo, clsk, ..."

In [9]:
# Reduce dataframe to just include date.
tweetsbyday_otly = otly_tweets_df["date"]

# Drop time form date
tweetsbyday_otly = pd.to_datetime(tweetsbyday_otly).dt.date
tweetsbyday_otly

0       2021-08-19
1       2021-08-19
2       2021-08-19
3       2021-08-19
4       2021-08-19
           ...
5371    2021-05-20
5372    2021-05-20
5373    2021-05-20
5374    2021-05-20
5375    2021-05-20
Name: date, Length: 5376, dtype: object

In [10]:
# Export twitter data to CSV.
tweetsbyday_otly.to_csv("tweetsbyday_otly.csv")